/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event sent from DES to the Partner app via the iframe or WebView
 */
export type DESEvent =
  | OnAccountProvisionRequestedEvent
  | OnAccountRequestedEvent
  | OnExitRequestedEvent
  | OnIdTokenDidExpireEvent
  | OnInvestmentAccountProvisionRequestedEvent
  | OnInvestmentSellRequestedEvent
  | OnPageReadyEvent
  | OnShareEvent
  | OnTelemetryEvent
  | OnTransferConsentRequestedEvent;

/**
 * Old account provisioning flow supporting one shared savings account per user
 */
export interface OnAccountProvisionRequestedEvent {
  event: "onAccountProvisionRequested";
  message: OnAccountProvisionRequestedMessage;
}
export interface OnAccountProvisionRequestedMessage {
  requestId: string;
}
/**
 * New account provisioning flow supporting multiple savings and performance accounts per user
 */
export interface OnAccountRequestedEvent {
  event: "onAccountRequested";
  message: OnAccountRequestedMessage;
}
export interface OnAccountRequestedMessage {
  requestId: string;
  dream: OnAccountRequestedMessageDream;
}
export interface OnAccountRequestedMessageDream {
  type: string;
  id: string;
  name: string;
  target_amount?: {
    cents: number;
    currency: string;
  };
  target_date?: string;
  user: {
    type: string;
    id: string;
    externalId: string;
  };
}
export interface OnExitRequestedEvent {
  event: "onExitRequested";
  message: OnExitRequestedMessage;
}
export interface OnExitRequestedMessage {}
export interface OnIdTokenDidExpireEvent {
  event: "onIdTokenDidExpire";
  message: OnIdTokenDidExpireMessage;
}
export interface OnIdTokenDidExpireMessage {
  requestId: string;
}
export interface OnInvestmentAccountProvisionRequestedEvent {
  event: "onInvestmentAccountProvisionRequested";
  message: OnInvestmentAccountProvisionRequestedMessage;
}
export interface OnInvestmentAccountProvisionRequestedMessage {
  requestId: string;
  accountId: string;
  callbackPath: string;
  cancelUrl: string;
  errorUrl: string;
}
export interface OnInvestmentSellRequestedEvent {
  event: "onInvestmentSellRequested";
  message: OnInvestmentSellRequestedMessage;
}
export interface OnInvestmentSellRequestedMessage {
  requestId: string;
  accountId: string;
  amount: {
    quantity: number;
    currency: string;
  };
  callbackUrl: string;
  cancelUrl: string;
  errorUrl: string;
}
export interface OnPageReadyEvent {
  event: "onPageReady";
  message: OnPageReadyMessage;
}
export interface OnPageReadyMessage {}
export interface OnShareEvent {
  event: "onShare";
  message: OnShareMessage;
}
export interface OnShareMessage {
  url: string;
  text: string;
  title: string;
}
export interface OnTelemetryEvent {
  event: "onTelemetry";
  message: OnTelemetryMessage;
}
export interface OnTelemetryMessage {
  name: "UserClicked";
  payload: OnTelemetryMessagePayload;
}
export interface OnTelemetryMessagePayload {
  [k: string]: unknown;
}
export interface OnTransferConsentRequestedEvent {
  event: "onTransferConsentRequested";
  message: OnTransferConsentRequestedMessage;
}
export interface OnTransferConsentRequestedMessage {
  requestId: string;
  consentId: string;
}
