/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event sent from the Partner app to DES via the iframe or WebView
 */
export type PartnerEvent =
  | AccountProvisionedEvent
  | InvestmentAccountProvisionInitiatedEvent
  | NavigateToEvent
  | OnAccountRequestedFailedEvent
  | OnAccountRequestedSucceededEvent
  | OnSignOutRequested
  | OnTransferConsentCancelledEvent
  | OnTransferConsentSucceededEvent
  | SessionKeepAliveEvent
  | UpdateTokenEvent;

export interface AccountProvisionedEvent {
  event: "accountProvisioned";
  message: AccountProvisionedMessage;
}
export interface AccountProvisionedMessage {
  requestId: string;
}
export interface InvestmentAccountProvisionInitiatedEvent {
  event: "investmentAccountProvisionInitiated";
  message: InvestmentAccountProvisionInitiatedMessage;
}
export interface InvestmentAccountProvisionInitiatedMessage {
  requestId: string;
  accountId: string;
}
export interface NavigateToEvent {
  event: "navigateTo";
  message: NavigateToMessage;
}
export interface NavigateToMessage {
  location: string;
}
export interface OnAccountRequestedFailedEvent {
  event: "onAccountRequestedFailed";
  message: OnAccountRequestedFailedMessage;
}
export interface OnAccountRequestedFailedMessage {
  requestId: string;
  reason: "cancelled" | "failed";
}
export interface OnAccountRequestedSucceededEvent {
  event: "onAccountRequestedSucceeded";
  message: OnAccountRequestedSucceededMessage;
}
export interface OnAccountRequestedSucceededMessage {
  requestId: string;
}
export interface OnSignOutRequested {
  event: "onSignOutRequested";
  message: OnSignOutRequestedMessage;
}
export interface OnSignOutRequestedMessage {}
export interface OnTransferConsentCancelledEvent {
  event: "onTransferConsentCancelled";
  message: OnTransferConsentCancelledMessage;
}
export interface OnTransferConsentCancelledMessage {
  requestId: string;
  consentId: string;
  reason: string;
}
export interface OnTransferConsentSucceededEvent {
  event: "onTransferConsentSucceeded";
  message: OnTransferConsentSucceededMessage;
}
export interface OnTransferConsentSucceededMessage {
  requestId: string;
  consentId: string;
  consentRef: string;
}
export interface SessionKeepAliveEvent {
  event: "sessionKeepAlive";
  message: SessionKeepAliveMessage;
}
export interface SessionKeepAliveMessage {}
export interface UpdateTokenEvent {
  event: "updateToken";
  message: UpdateTokenMessage;
}
export interface UpdateTokenMessage {
  requestId: string;
  idToken: string;
}
